#!/usr/bin/env python3

"""
GPU 병렬 처리에서 이미지를 (W/G) × H로 나누는 코드 위치 분석
"""

print("=" * 70)
print("GPU 병렬 처리 이미지 분할 코드 위치")
print("=" * 70)
print()

print("1. Python 쪽 - 타일 분할 전략 설정")
print("-" * 50)
print("📁 파일: /workspace/Grendel-GS/gaussian_renderer/workload_division.py")
print()
print("🔹 Line 52-57: get_evenly_division_pos()")
print("   균등 분할 로직:")
print("   ```python")
print("   if tile_num % utils.MP_GROUP.size() == 0:")
print("       cnt = tile_num // utils.MP_GROUP.size()")
print("   else:")
print("       cnt = tile_num // utils.MP_GROUP.size() + 1")
print("   division_pos = [cnt * i for i in range(utils.MP_GROUP.size())] + [tile_num]")
print("   ```")
print("   → 전체 타일을 GPU 개수로 균등 분할")
print()

print("🔹 Line 130-132: DivisionStrategy.__init__()")
print("   ```python")
print("   self.division_pos = division_pos_heuristic(")
print("       heuristic, self.tile_x * self.tile_y, self.world_size")
print("   )```")
print("   → 휴리스틱 기반 동적 분할")
print()

print("🔹 Line 137-139: get_compute_locally()")
print("   ```python")
print("   tile_ids_l, tile_ids_r = (")
print("       self.division_pos[self.rank],")
print("       self.division_pos[self.rank + 1],")
print("   )```")
print("   → 각 GPU의 담당 타일 범위 계산")
print()

print("2. CUDA 쪽 - 실제 타일별 렌더링")
print("-" * 50)
print("📁 파일: /workspace/Grendel-GS/submodules/diff-gaussian-rasterization/rasterize_points.cu")
print()
print("🔹 Line 419: 전체 타일 그리드 계산")
print("   ```cpp")
print("   dim3 tile_grid((width + BLOCK_X - 1) / BLOCK_X, (height + BLOCK_Y - 1) / BLOCK_Y, 1);")
print("   ```")
print("   → TILE_X = (W + 15) / 16, TILE_Y = (H + 15) / 16")
print()

print("🔹 Line 430-444: 각 GPU별 타일 범위 확인")
print("   ```cpp")
print("   for (int rk = 0; rk < world_size; rk++) {")
print("       int tile_l = *(dist_global_strategy+rk);")
print("       int tile_r = *(dist_global_strategy+rk+1);")
print("       // 현재 가우시안이 이 GPU 범위에 영향을 주는지 확인")
print("   }```")
print("   → 각 GPU는 tile_l ~ tile_r 범위만 처리")
print()

print("3. 타일→픽셀 변환")
print("-" * 50)
print("📁 파일: /workspace/Grendel-GS/submodules/diff-gaussian-rasterization/cuda_rasterizer/auxiliary.h")
print()
print("🔹 Line 105-109: getLocalPixelRect()")
print("   ```cpp")
print("   local_pixel_rect_min.x = local_tile_rect_min.x * BLOCK_X;")
print("   local_pixel_rect_max.x = min(image_width, local_tile_rect_max.x * BLOCK_X);")
print("   ```")
print("   → 타일 좌표를 픽셀 좌표로 변환")
print()

print("4. 분할 결과")
print("-" * 50)
print("• 전체 이미지: W × H")
print("• 전체 타일: TILE_X × TILE_Y")
print("• GPU 0: 타일 [0, cnt) → 픽셀 [0, cnt*16)")
print("• GPU 1: 타일 [cnt, 2*cnt) → 픽셀 [cnt*16, 2*cnt*16)")
print("• ...")
print("• 각 GPU 처리 크기: 약 (W/G) × H")
print()

print("🔥 핵심:")
print("   타일을 X축(width) 방향으로만 분할하므로")
print("   각 GPU는 (W/G) × H 크기의 이미지 영역을 담당!")
print()

print("=" * 70)