#!/usr/bin/env python3

"""
Loss 계산에서 (H/G) × W 이미지 크기가 결정되는 과정 분석
"""

print("=" * 70)
print("Loss 계산에서 이미지 크기 결정 과정")
print("=" * 70)
print()

print("🔍 발견한 핵심 흐름:")
print("-" * 50)
print()

print("1️⃣ 타일 분할 (workload_division.py:891)")
print("   division_pos_heuristic() 호출")
print("   → GPU별 타일 범위 결정")
print("   예: [0, 360, 721, 1082] (타일 인덱스)")
print()

print("2️⃣ compute_locally 생성 (workload_division.py:783-791)")
print("   ```python")
print("   tile_ids_l, tile_ids_r = (")
print("       self.division_pos[rank] * utils.TILE_X,  # 타일→1D 인덱스 변환")
print("       self.division_pos[rank + 1] * utils.TILE_X")
print("   )")
print("   compute_locally = torch.zeros(utils.TILE_Y * utils.TILE_X, dtype=torch.bool)")
print("   compute_locally[tile_ids_l:tile_ids_r] = True")
print("   compute_locally = compute_locally.view(utils.TILE_Y, utils.TILE_X)  # 2D로 변환")
print("   ```")
print()

print("3️⃣ 렌더링 (gaussian_renderer/__init__.py:490-501)")
print("   ```python")
print("   rendered_image = rasterizer.render_gaussians(")
print("       compute_locally=compute_locally,  # 각 GPU 담당 타일 마스크")
print("       ...)")
print("   ```")
print("   → 렌더링 결과는 compute_locally 영역만 포함")
print()

print("4️⃣ 타일→픽셀 변환 (loss_distribution.py:633-640)")
print("   ```python")
print("   first_tile_y, first_tile_x = (")
print("       tile_ids_l // strategy.tile_x,  # 타일 좌표 계산")
print("       tile_ids_l % strategy.tile_x")
print("   )")
print("   first_pixel_y, first_pixel_x = (")
print("       first_tile_y * utils.BLOCK_Y,   # 픽셀 좌표 변환")
print("       first_tile_x * utils.BLOCK_X")
print("   )")
print("   ```")
print()

print("5️⃣ Loss 계산 입력 (loss_distribution.py:601)")
print("   ```python")
print("   def fast_distributed_loss_computation(")
print("       image,           # 렌더링된 부분 이미지")
print("       viewpoint_cam,   # 전체 이미지 정보")
print("       compute_locally, # GPU 담당 타일 마스크")
print("       strategy,        # 분할 전략")
print("       ...)")
print("   ```")
print()

print("🎯 핵심 답변:")
print("=" * 50)
print("📐 렌더링 출력 크기:")
print("   • CUDA 렌더링: compute_locally에 따라 결정")
print("   • 각 GPU는 자신이 담당하는 타일 영역만 렌더링")
print("   • 타일 범위 → 픽셀 범위 변환: tile * BLOCK_SIZE")
print()
print("📊 실제 이미지 크기:")
print("   • 전체: TILE_Y × TILE_X = (H/16) × (W/16) 타일")
print("   • GPU 0: 타일 [0, 360] → 픽셀 영역")
print("   • GPU 1: 타일 [360, 721] → 픽셀 영역")
print("   • GPU 2: 타일 [721, 1082] → 픽셀 영역")
print()
print("💡 결론:")
print("   loss 계산에 들어가는 이미지 크기는")
print("   렌더링 단계에서 compute_locally 마스크에 의해")
print("   각 GPU별로 (W/G) × H 크기로 결정됨!")
print()
print("=" * 70)