#!/usr/bin/env python3

"""
메모리 사용량 분석 및 해결책
"""

print("=" * 60)
print("CUDA OOM 문제 분석")
print("=" * 60)
print()
print("748 MiB 요구 사항 분석:")
print("-" * 40)
print()
print("이미지 크기가 4096x4096이라고 가정하면:")
print("- 원본 연산: ssim_loss * mask")
print("- ssim_loss: (3, 4096, 4096) = 3 * 16M * 4 bytes = 192 MiB")
print("- mask.view: (1, 4096, 4096) = 16M * 4 bytes = 64 MiB")
print("- 결과 텐서: (3, 4096, 4096) = 192 MiB")
print("- Gradient 저장: 192 MiB")
print("- 임시 버퍼: ~100 MiB")
print("총합: ~748 MiB")
print()
print("문제:")
print("-" * 40)
print("1. GPU 메모리가 거의 가득 참 (23.43/23.46 GiB)")
print("2. 새로운 텐서 할당 시 연속된 메모리 블록 필요")
print("3. 메모리 단편화로 인해 작은 여유 공간에서도 실패")
print()
print("적용한 해결책:")
print("-" * 40)
print("1. In-place 연산 사용 (*= 대신 *)")
print("   - 새 텐서 생성 없음")
print("   - 메모리 사용량 50% 감소")
print()
print("2. view() 사용 (unsqueeze() 대신)")
print("   - 메모리 복사 없이 shape만 변경")
print("   - 더 효율적인 브로드캐스팅")
print()
print("추가 권장사항:")
print("-" * 40)
print("1. Batch size 줄이기")
print("2. Gradient accumulation 사용")
print("3. Mixed precision training (FP16)")
print("4. torch.cuda.empty_cache() 주기적 호출")
print("5. Gradient checkpointing 활성화")
print()
print("=" * 60)